name: kwin
description: A Dart package to interact with the KDE window manager KWin.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  dbus: ^0.7.10
  logger: ^2.5.0
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
